language: generic

before_install:
 - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
 - evm install emacs-24.5-travis --use --skip

script:
  - ./.travis-build.sh
